"""Add Vizite table

Revision ID: 10283d8cac4a
Revises: 644994852dfd
Create Date: 2025-06-03 22:37:33.774638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10283d8cac4a'
down_revision = '644994852dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locuri__vizitate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('nr_vizite', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat'),
    sa.UniqueConstraint('lng')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locuri__vizitate')
    # ### end Alembic commands ###
