"""Modificare structura de autentificare in Nume si Parola

Revision ID: 64469005c49c
Revises: 
Create Date: 2025-02-13 16:31:40.289825

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64469005c49c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))
        batch_op.drop_index('phone')
        batch_op.drop_column('voice_hash')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authentification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('voice_hash', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_index('phone', ['phone'], unique=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###
