"""Add Route table

Revision ID: 644994852dfd
Revises: 64469005c49c
Create Date: 2025-05-13 18:00:34.033140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '644994852dfd'
down_revision = '64469005c49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ziua', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora', sa.Time(), nullable=False),
    sa.Column('locatie_start_lat', sa.Float(), nullable=False),
    sa.Column('locatie_start_lng', sa.Float(), nullable=False),
    sa.Column('locatie_end_lat', sa.Float(), nullable=False),
    sa.Column('locatie_end_lng', sa.Float(), nullable=False),
    sa.Column('locatie_start_nume', sa.String(length=255), nullable=False),
    sa.Column('locatie_end_nume', sa.String(length=255), nullable=False),
    sa.Column('opriri', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route')
    # ### end Alembic commands ###
