"""Add unique constraint on lat/lng

Revision ID: aa46766d88b2
Revises: ab54ebdc104c
Create Date: 2025-06-08 13:53:43.235986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa46766d88b2'
down_revision = 'ab54ebdc104c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locuri_vizitate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nume_utilizator', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('nr_vizite', sa.Integer(), nullable=False),
    sa.Column('nume_loc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat', 'lng', name='unique_lat_lng')
    )
    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.drop_index('lat')
        batch_op.drop_index('lng')

    op.drop_table('locuri__vizitate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locuri__vizitate',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=False),
    sa.Column('lng', mysql.FLOAT(), nullable=False),
    sa.Column('nr_vizite', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nume_utilizator', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('nume_loc', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.create_index('lng', ['lng'], unique=True)
        batch_op.create_index('lat', ['lat'], unique=True)

    op.drop_table('locuri_vizitate')
    # ### end Alembic commands ###
