"""adaugat coloana nume_loc in locuri_vizitate

Revision ID: ab54ebdc104c
Revises: e2f0ce3ed048
Create Date: 2025-06-07 18:31:47.864948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab54ebdc104c'
down_revision = 'e2f0ce3ed048'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nume_loc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.drop_column('nume_loc')

    # ### end Alembic commands ###
