"""actualizare tabela route si locuri_vizitate

Revision ID: e2f0ce3ed048
Revises: 10283d8cac4a
Create Date: 2025-06-04 21:49:27.990697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f0ce3ed048'
down_revision = '10283d8cac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nume_utilizator', sa.String(length=255), nullable=False))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nume_utilizator', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('nume_utilizator')

    with op.batch_alter_table('locuri__vizitate', schema=None) as batch_op:
        batch_op.drop_column('nume_utilizator')

    # ### end Alembic commands ###
